CREATE TABLE NATIONAL (
    NATIONAL_CODE   CHAR(2)       CONSTRAINT PK_NATIONAL_CODE     PRIMARY KEY
    , NATIONAL_NAME VARCHAR2(35)
);

COMMENT ON TABLE NATIONAL IS '국가';

DROP TABLE LOCATION;

CREATE TABLE LOCATION (
    LOCAL_CODE      CHAR(2)         CONSTRAINT PK_LOCAL_CODE                        PRIMARY KEY
    , NATIONAL_CODE CHAR(2)         REFERENCES TESTUSER.NATIONAL (NATIONAL_CODE)    NOT NULL
    , LOCAL_NAME    VARCHAR2(40)
);

COMMENT ON TABLE LOCATION IS '지역';

CREATE TABLE DEPT (
    DEPT_ID         CHAR(2)         CONSTRAINT PK_DEPT_ID               PRIMARY KEY
    , DEPT_TITLE    VARCHAR2(35)
    , LOCATION_ID   CHAR(2)         REFERENCES LOCATION (LOCAL_CODE)    NOT NULL
);

COMMENT ON TABLE DEPT IS '부서';

CREATE TABLE JOB(
    JOB_CODE        CHAR(2)         CONSTRAINT PK_JOB_CODE              PRIMARY KEY
    , JOB_NAME      VARCHAR2(35)
);

COMMENT ON TABLE JOB IS '직급';

CREATE TABLE EMP (
    EMP_ID          VARCHAR2(3)     CONSTRAINT PK_EMP_ID                PRIMARY KEY
    , EMP_NAME      VARCHAR2(20)    CONSTRAINT EMP_NAME                 NOT NULL
    , EMP_NO        CHAR(14)        CONSTRAINT EMP_NO                   NOT NULL
    , EMAIL         VARCHAR2(25)
    , PHONE         VARCHAR2(12)
    , DEPT_CODE     CHAR(2)         REFERENCES DEPT (DEPT_ID)           NOT NULL
    , JOB_CODE      CHAR(2)         REFERENCES JOB (JOB_CODE)           NOT NULL
    , SALARY        NUMBER
    , BONUS         NUMBER
    , MANAGER_ID    VARCHAR2(3)     REFERENCES EMP (EMP_ID)
    , HIRE_DATE     DATE
    , ENT_DATE      DATE
    , ENT_YN        CHAR(1)
);

COMMENT ON TABLE EMP IS '사원';

CREATE TABLE SAL_GRADE (
    SAL_LEVEL   CHAR(2)
    , MIN_SAL   NUMBER
    , MAX_SAL   NUMBER
);

COMMENT ON TABLE SAL_GRADE IS '급여등급';